# Generated by Django 5.1.6 on 2025-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продавец'),
        ),
    ]
